name: Build and Deploy
# 监听 master 分支上的 push 事件
on:
  push:
    branches:
      - main
jobs:
  build:
    # 构建环境使用 ubuntu
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      # 官方action, 将代码拉取到虚拟机
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 安装node.js
      # - name: Use Node.js
      #   uses: actions/setup-node@v6
      #   with:
      #     node-version: 24
      # 安装pnpm
      # - name: Install pnpm
      #   run: npm install -g pnpm
      - name: Source ~/.bashrc
        run: |
          source ~/.bashrc
      # 下载依赖、打包项目
      - name: Install and Build
        run: |
          pnpm install
          pnpm build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clean output directory
        run: |
          rm -rf /home/ubuntu/fhb/jyuacmblog
          mkdir -p /home/ubuntu/fhb/jyuacmblog

      - name: Copy build outputs
        run: |
          cp -r dist/* /home/ubuntu/fhb/jyuacmblog

      # 部署到服务器
      # - name: Upload to Deploy Server
      #   uses: appleboy/scp-action@master
      #   with:
      #     # 服务器域名
      #     host: ${{ secrets.SERVER_HOST }}
      #     # 服务器用户名
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     # 服务器密码
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     # 服务器端口
      #     port: ${{ secrets.SERVER_PORT }}
      #     # 指定上传的文件目录(项目配置的打包目录名称)
      #     source: './dist/*'
      #     # 指定上传服务器目录
      #     target: '/home/ubuntu/fhb/jyuacmblog'
      #     # 解压时覆盖现有文件
      #     overwrite: true
      #     # 删除指定数量的前导路径元素
      #     strip_components: 1
